package com.example.brendancode.demoTest;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class MovieReviewTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void movieReviewTest() {
    driver.get("http://44.201.145.185:3000/");
    driver.manage().window().maximize();
    driver.findElement(By.cssSelector(".film-container:nth-child(4) div:nth-child(7) input:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".film-container:nth-child(4) div:nth-child(7) input:nth-child(1)")).sendKeys("4");
    driver.findElement(By.cssSelector(".film-container:nth-child(4) div:nth-child(7) input:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".film-container:nth-child(4) div:nth-child(7) input:nth-child(2)")).sendKeys("Second review for affair");
    driver.findElement(By.cssSelector(".film-container:nth-child(4) div:nth-child(7) button")).click();
    driver.findElement(By.cssSelector(".film-container:nth-child(4) div:nth-child(9) input")).click();
    driver.findElement(By.cssSelector(".film-container:nth-child(4) div:nth-child(9) input")).sendKeys("12");
    driver.findElement(By.cssSelector(".film-container:nth-child(4) div:nth-child(9) button")).click();
    driver.findElement(By.cssSelector(".searchBar > input")).click();
    driver.findElement(By.cssSelector(".searchBar > input")).sendKeys("ace");
  }
}
